# -*- coding: utf-8 -*-
"""video_Transcribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z--F_gsLl335R4LnI2m_NItAaathZWlo

**Trancibe using whisper from OpenAI**
"""

! pip install pytube

from pytube import YouTube

link='https://youtu.be/yOMneQWaFaI?si=IXFyf72-Zre6JZp8'

try:
    yt=YouTube(link)
except:
    print("connection error")

yt.streams.filter(file_extension="mp4")

stream=yt.streams.get_by_itag(140)

stream.download('','timetravel_story.mp4')

!pip install git+https://github.com/openai/whisper.git

!pip install jiwer

import whisper

model = whisper.load_model("base")
result = model.transcribe("timetravel_story.mp4")
print(result["text"])

!pip install deep_Translator

import whisper
import soundfile as sf

# Load the custom audio file
audio_file = "/content/audio.wav"

# Initialize the Whisper model
model = whisper.load_model("base")

# Perform speech recognition on the audio file
result = model.transcribe(audio_file)

# Print the transcription result
print(result["text"])

import whisper
from deep_translator import GoogleTranslator

# Load the Whisper model
model = whisper.load_model("base")

# Transcribe the audio
result = model.transcribe("/content/audio.wav")

# Create a GoogleTranslator object
translator = GoogleTranslator(target='ur')

# Translate the extracted text
translated_text = translator.translate(result["text"])

# Print the translated text
print(translated_text)